#!/usr/bin/env python3
"""
Catch drift between the hand-maintained email brief and the board-approved
full issue before the Beehiiv draft is loaded.

    python3 check_email_consistency.py 2026-10-08

Why this exists: `<date>.email.html` is written by hand, separately from
`<date>.both.html` -- it is NOT generated by build.py, so a correction
made to both.html during board review (a renamed event, a fixed date)
has no mechanism to propagate to the email brief. This bit for real on
2026-10-08: the board corrected the Serbia election date (Oct 24 -> 25)
and the St. George retreat's Serbian name ("Јесењи реколект" -> "Јесење
духовно сабрање") in both.html, but email.html still had both stale
values when it was loaded into the Beehiiv draft -- caught only because
the draft was read closely during that step, not because anything
flagged it automatically.

Two checks, against the VISIBLE TEXT only (HTML tags/attributes stripped,
so a UTM-tagged href doesn't trip the word check):

  1. DATE NUMBERS (hard failure) -- every day-of-month mentioned near
     "Oct"/"окт" in email.html must also appear near "Oct"/"окт"
     somewhere in both.html. A date in the brief that doesn't exist
     anywhere in the approved full issue is almost certainly stale.

  2. STALE WORDS (soft warning, not a failure) -- any Cyrillic or Latin
     word of 5+ characters in email.html that does not appear anywhere
     in both.html at all. This is advisory, not a hard gate: email.html
     legitimately condenses/rephrases things, so some unique vocabulary
     is expected (its own Special Assembly callout, footer boilerplate,
     etc.) -- but a flagged word is worth a human glance before sending,
     since it's exactly the shape of signal that caught the retreat
     rename. Pass --strict to make this a hard failure too.

Run this BEFORE loading the Beehiiv draft (README Step 5), right after
add_utm_tags.py.
"""
import re
import sys
from pathlib import Path

from bs4 import BeautifulSoup

DATE_NUM_PATTERNS = [
    r"Oct\.?\s+(\d{1,2})\b",
    r"(\d{1,2})\.\s*окт(?:обра|обар)?\b",
]

WORD_PATTERN = re.compile(r"[A-Za-zА-Яа-яЂђЋћЧчЏџШшЖжЉљЊњ]{5,}")

# Visible-text words that legitimately appear only in the email brief --
# not a sign of staleness, just the brief's own framing/boilerplate.
KNOWN_EMAIL_ONLY = {
    "issue", "brief", "week's", "Messenger", "This", "about", "Church",
    "Serbian", "Orthodox", "Nicholas", "Elkins", "Stahr", "receiving",
    "family", "preferences", "Unsubscribe", "Update", "powered", "beehiiv",
}


URL_PATTERN = re.compile(r"https?://\S+")


def visible_text(path):
    soup = BeautifulSoup(path.read_text(encoding="utf-8"), "html.parser")
    for tag in soup(["style", "script"]):
        tag.decompose()
    # strip URLs shown as literal link text (e.g. a fallback "https://..."
    # line under a button) -- those aren't prose, they're link targets.
    return URL_PATTERN.sub(" ", soup.get_text(" "))


def main():
    args = sys.argv[1:]
    strict = "--strict" in args
    args = [a for a in args if a != "--strict"]
    if len(args) != 1:
        print(__doc__)
        sys.exit(1)
    date = args[0]
    both_path = Path(f"drafts/{date}.both.html")
    email_path = Path(f"drafts/{date}.email.html")
    for p in (both_path, email_path):
        if not p.exists():
            print(f"missing file: {p}")
            sys.exit(1)

    both_text = visible_text(both_path)
    email_text = visible_text(email_path)

    problems = []
    warnings = []

    # 1. Date numbers
    both_dates = set()
    email_dates = set()
    for pat in DATE_NUM_PATTERNS:
        both_dates |= set(re.findall(pat, both_text))
        email_dates |= set(re.findall(pat, email_text))
    stale_dates = email_dates - both_dates
    if stale_dates:
        problems.append(
            f"email.html mentions Oct day(s) {sorted(stale_dates)} near 'Oct'/'окт' "
            f"that don't appear anywhere in both.html (approved dates: {sorted(both_dates)}) "
            f"-- likely a stale date left over from before a board correction"
        )

    # 2. Stale words
    both_words = set(WORD_PATTERN.findall(both_text))
    email_words = set(WORD_PATTERN.findall(email_text))
    stale_words = sorted(email_words - both_words - KNOWN_EMAIL_ONLY)
    if stale_words:
        msg = f"word(s) in email.html not found anywhere in both.html: {stale_words}"
        if strict:
            problems.append(msg)
        else:
            warnings.append(msg)

    if warnings:
        print(f"WARNINGS -- {len(warnings)} (advisory, review before sending):")
        for w in warnings:
            print(f"  - {w}")

    if problems:
        print(f"\nFAILED -- {len(problems)} issue(s):")
        for p in problems:
            print(f"  - {p}")
        sys.exit(1)

    print(f"\nOK -- {email_path} is consistent with {both_path}"
          + (" (no warnings)" if not warnings else ""))


if __name__ == "__main__":
    main()
